services:
  backend:
    build: ./backend-python
    ports:
      - "8000:8000"
    volumes:
      - ./backend-python:/app
    restart: always

  frontend:
    build: ./frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

volumes:
  frontend_node_modules:
